# Facebook dependencies
[mcrouter]
src.manual = "v2023.08.07.00"
fetch.github = "facebook/mcrouter"

[fizz]
src.manual = "v2023.08.07.00"
fetch.github = "facebookincubator/fizz"

[folly]
src.manual = "v2023.08.07.00"
fetch.github = "facebook/folly"

[wangle]
src.manual = "v2023.08.07.00"
fetch.github = "facebook/wangle"

[mvfst]
src.manual = "v2023.08.07.00"
fetch.github = "facebook/mvfst"

[fbthrift]
src.manual = "v2023.08.07.00"
fetch.github = "facebook/fbthrift"

# Base containers
[alpine-x86_64-linux]
src.container = "library/alpine"
src.include_regex = "3.18.3"
fetch.docker = "library/alpine"
docker.arch = "amd64"

[alpine-aarch64-linux]
src.container = "library/alpine"
src.include_regex = "3.18.3"
fetch.docker = "library/alpine"
docker.arch = "arm64"