# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  fbthrift = {
    pname = "fbthrift";
    version = "v2023.08.07.00";
    src = fetchFromGitHub {
      owner = "facebook";
      repo = "fbthrift";
      rev = "v2023.08.07.00";
      fetchSubmodules = false;
      sha256 = "sha256-99wYSiEzSJu8unE4tAMg4161cXHZvP93uOfofWircvs=";
    };
  };
  fizz = {
    pname = "fizz";
    version = "v2023.08.07.00";
    src = fetchFromGitHub {
      owner = "facebookincubator";
      repo = "fizz";
      rev = "v2023.08.07.00";
      fetchSubmodules = false;
      sha256 = "sha256-ijrCdkR5EqprFQSD+fxPK4XR2EjOXpuntH/HbTf8LvM=";
    };
  };
  folly = {
    pname = "folly";
    version = "v2023.08.07.00";
    src = fetchFromGitHub {
      owner = "facebook";
      repo = "folly";
      rev = "v2023.08.07.00";
      fetchSubmodules = false;
      sha256 = "sha256-4H30yGD9Z4VsqGhOtFS7mpY6RUuUFpLidH61A8ETqzg=";
    };
  };
  mcrouter = {
    pname = "mcrouter";
    version = "v2023.08.07.00";
    src = fetchFromGitHub {
      owner = "facebook";
      repo = "mcrouter";
      rev = "v2023.08.07.00";
      fetchSubmodules = false;
      sha256 = "sha256-+8Dcj1X9OC5wbHkvqC6ahrcfALpg7sUYkoJnpOTG4M0=";
    };
  };
  mvfst = {
    pname = "mvfst";
    version = "v2023.08.07.00";
    src = fetchFromGitHub {
      owner = "facebook";
      repo = "mvfst";
      rev = "v2023.08.07.00";
      fetchSubmodules = false;
      sha256 = "sha256-tLpLXQdJBec+9EN7c3bj1vniXVM3iicBTfP3QDIjPiQ=";
    };
  };
  wangle = {
    pname = "wangle";
    version = "v2023.08.07.00";
    src = fetchFromGitHub {
      owner = "facebook";
      repo = "wangle";
      rev = "v2023.08.07.00";
      fetchSubmodules = false;
      sha256 = "sha256-giiqo0MMvlNCJnM/lIRQ8CoCHELOZazj4LB9HXt8Svc=";
    };
  };
}
