# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  alpine-aarch64-linux = {
    pname = "alpine-aarch64-linux";
    version = "3.18.3";
    src = dockerTools.pullImage {
      imageName = "library/alpine";
      imageDigest = "sha256:7144f7bab3d4c2648d7e59409f15ec52a18006a128c733fcff20d3a4a54ba44a";
      sha256 = "sha256-UMizyCBsYy7Lpa7U4VocNOtm7QGYOYvcTIkWj6V4bvc=";
      finalImageTag = "3.18.3";
      arch = "arm64";
    };
  };
  alpine-x86_64-linux = {
    pname = "alpine-x86_64-linux";
    version = "3.18.3";
    src = dockerTools.pullImage {
      imageName = "library/alpine";
      imageDigest = "sha256:7144f7bab3d4c2648d7e59409f15ec52a18006a128c733fcff20d3a4a54ba44a";
      sha256 = "sha256-3K73rB1MoF/co3J61jvGPacxClxswsNAdQ2wDvlZLIs=";
      finalImageTag = "3.18.3";
      arch = "amd64";
    };
  };
  fbthrift = {
    pname = "fbthrift";
    version = "v2023.08.07.00";
    src = fetchFromGitHub {
      owner = "facebook";
      repo = "fbthrift";
      rev = "v2023.08.07.00";
      fetchSubmodules = false;
      sha256 = "sha256-99wYSiEzSJu8unE4tAMg4161cXHZvP93uOfofWircvs=";
    };
  };
  fizz = {
    pname = "fizz";
    version = "v2023.08.07.00";
    src = fetchFromGitHub {
      owner = "facebookincubator";
      repo = "fizz";
      rev = "v2023.08.07.00";
      fetchSubmodules = false;
      sha256 = "sha256-ijrCdkR5EqprFQSD+fxPK4XR2EjOXpuntH/HbTf8LvM=";
    };
  };
  folly = {
    pname = "folly";
    version = "v2023.08.07.00";
    src = fetchFromGitHub {
      owner = "facebook";
      repo = "folly";
      rev = "v2023.08.07.00";
      fetchSubmodules = false;
      sha256 = "sha256-4H30yGD9Z4VsqGhOtFS7mpY6RUuUFpLidH61A8ETqzg=";
    };
  };
  mcrouter = {
    pname = "mcrouter";
    version = "v2023.08.07.00";
    src = fetchFromGitHub {
      owner = "facebook";
      repo = "mcrouter";
      rev = "v2023.08.07.00";
      fetchSubmodules = false;
      sha256 = "sha256-+8Dcj1X9OC5wbHkvqC6ahrcfALpg7sUYkoJnpOTG4M0=";
    };
  };
  mvfst = {
    pname = "mvfst";
    version = "v2023.08.07.00";
    src = fetchFromGitHub {
      owner = "facebook";
      repo = "mvfst";
      rev = "v2023.08.07.00";
      fetchSubmodules = false;
      sha256 = "sha256-tLpLXQdJBec+9EN7c3bj1vniXVM3iicBTfP3QDIjPiQ=";
    };
  };
  wangle = {
    pname = "wangle";
    version = "v2023.08.07.00";
    src = fetchFromGitHub {
      owner = "facebook";
      repo = "wangle";
      rev = "v2023.08.07.00";
      fetchSubmodules = false;
      sha256 = "sha256-giiqo0MMvlNCJnM/lIRQ8CoCHELOZazj4LB9HXt8Svc=";
    };
  };
}
