name: CI

env:
  CACHIX_CACHE_NAME: remi-gelinas-mcrouter
  NIX_INSTALL_URL: https://github.com/nix-community/nix-unstable-installer/releases/download/nix-2.17.0pre20230609_03f9ff6/install
  EXTRA_NIX_CONFIG: |
    experimental-features = nix-command flakes
    substituters = https://cache.nixos.org/ https://nix-community.cachix.org https://remi-gelinas-mcrouter.cachix.org
    trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= remi-gelinas-mcrouter.cachix.org-1:ZBe+WPJ0eWuRfeXR4FREkU/22iKabCgz+wMr8TgPeo8=


on:
  push:
    branches:
      - remi-gelinas/initial-docker-workflows
  # pull_request:
  #   branches:
  #     - trunk
  # merge_group:
  #   branches:
  #     - trunk

concurrency:
  group: ${{ github.repository }}-${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  set-env:
    runs-on: ubuntu-latest
    outputs:
      CACHIX_CACHE_NAME: ${{ steps.env.outputs.CACHIX_CACHE_NAME }}
    steps:
      - id: env
        run: |
          echo "CACHIX_CACHE_NAME=${{ env.CACHIX_CACHE_NAME }}" >> "$GITHUB_OUTPUT"

  alejandra:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          install_url: ${{ env.NIX_INSTALL_URL }}
          extra_nix_config: "${{ env.EXTRA_NIX_CONFIG }}"
      - uses: actions/checkout@v3.5.3
      - name: Check formatting
        run: |
          nix-shell --arg packages 'pkgs: [ pkgs.alejandra ]' --run 'alejandra --check .'

  statix:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          install_url: ${{ env.NIX_INSTALL_URL }}
          extra_nix_config: "${{ env.EXTRA_NIX_CONFIG }}"
      - uses: actions/checkout@v3.5.3
      - name: Static code analysis
        run: |
          nix-shell --arg packages 'pkgs: [ pkgs.statix ]' --run 'statix check .'

  deadnix:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          install_url: ${{ env.NIX_INSTALL_URL }}
          extra_nix_config: "${{ env.EXTRA_NIX_CONFIG }}"
      - uses: actions/checkout@v3.5.3
      - name: Check for dead code
        run: |
          nix-shell --arg packages 'pkgs: [ pkgs.deadnix ]' --run 'deadnix -f --exclude ./_sources/generated.nix'

  nixpkgs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Check flake input
        uses: DeterminateSystems/flake-checker-action@v5
        with:
          send-statistics: false

  # Jobs are split up to avoid the 6 hour job timeout
  folly:
    needs: set-env
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    uses: ./.github/workflows/build_attribute.yaml
    with:
      cacheName: ${{ needs.set-env.outputs.CACHIX_CACHE_NAME }}
      platform: ${{ matrix.platform }}
      attribute: folly
    secrets:
      cachixAuthToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

  fizz:
    needs: [set-env, folly]
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    uses: ./.github/workflows/build_attribute.yaml
    with:
      cacheName: ${{ needs.set-env.outputs.CACHIX_CACHE_NAME }}
      platform: ${{ matrix.platform }}
      attribute: fizz
    secrets:
      cachixAuthToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

  wangle:
    needs: [set-env, fizz, folly]
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    uses: ./.github/workflows/build_attribute.yaml
    with:
      cacheName: ${{ needs.set-env.outputs.CACHIX_CACHE_NAME }}
      platform: ${{ matrix.platform }}
      attribute: wangle
    secrets:
      cachixAuthToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

  mvfst:
    needs: [set-env, fizz, folly]
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    uses: ./.github/workflows/build_attribute.yaml
    with:
      cacheName: ${{ needs.set-env.outputs.CACHIX_CACHE_NAME }}
      platform: ${{ matrix.platform }}
      attribute: mvfst
    secrets:
      cachixAuthToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

  fbthrift:
    needs: [set-env, wangle, fizz, folly, mvfst]
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    uses: ./.github/workflows/build_attribute.yaml
    with:
      cacheName: ${{ needs.set-env.outputs.CACHIX_CACHE_NAME }}
      platform: ${{ matrix.platform }}
      attribute: fbthrift
    secrets:
      cachixAuthToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

  mcrouter:
    needs: [fbthrift, mvfst, wangle, fizz, folly]
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    uses: ./.github/workflows/build_attribute.yaml
    with:
      cacheName: ${{ needs.set-env.outputs.CACHIX_CACHE_NAME }}
      platform: ${{ matrix.platform }}
      attribute: mcrouter
    secrets:
      cachixAuthToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
